package org.campware.dream.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Jul 29 08:38:49 CEST 2004]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Region
 */
public abstract class BaseRegion extends BaseObject
{
    /** The Peer class */
    private static final RegionPeer peer =
        new RegionPeer();

                  
        /**
         * The value for the region_id field
         */
        private int region_id;
              
        /**
         * The value for the region_name field
         */
        private String region_name;
      
      
        /**
         * Get the RegionId
         *
         * @return int
         */
        public int getRegionId()
        {
            return region_id;
        }

                                                                              
        /**
         * Set the value of RegionId
         *
         * @param v new value
         */
        public void setRegionId(int v) throws TorqueException
        {
          


         if (this.region_id != v)
        {
             this.region_id = v;
            setModified(true);
        }

                  
                                                  
              // update associated Distributor
              if (collDistributors != null)
              {
                  for (int i = 0; i < collDistributors.size(); i++)
                  {
                      ((Distributor) collDistributors.get(i))
                          .setRegionId(v);
                  }
              }
                                                              
              // update associated Location
              if (collLocations != null)
              {
                  for (int i = 0; i < collLocations.size(); i++)
                  {
                      ((Location) collLocations.get(i))
                          .setRegionId(v);
                  }
              }
                                   }


        /**
         * Get the RegionName
         *
         * @return String
         */
        public String getRegionName()
        {
            return region_name;
        }

                                            
        /**
         * Set the value of RegionName
         *
         * @param v new value
         */
        public void setRegionName(String v) 
        {
          


         if (!ObjectUtils.equals(this.region_name, v))
        {
             this.region_name = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collDistributors
     */
    protected List collDistributors;

    /**
     * Temporary storage of collDistributors to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initDistributors()
    {
        if (collDistributors == null)
        {
            collDistributors = new ArrayList();
        }
    }

    /**
     * Method called to associate a Distributor object to this object
     * through the Distributor foreign key attribute
     *
     * @param l Distributor
     * @throws TorqueException
     */
    public void addDistributor(Distributor l) throws TorqueException
    {
        getDistributors().add(l);
        l.setRegion((Region) this);
    }

    /**
     * The criteria used to select the current contents of collDistributors
     */
    private Criteria lastDistributorsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDistributors(new Criteria())
     *
     * @throws TorqueException
     */
    public List getDistributors() throws TorqueException
    {
        if (collDistributors == null)
        {
            collDistributors = getDistributors(new Criteria(10));
        }
        return collDistributors;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Region has previously
     * been saved, it will retrieve related Distributors from storage.
     * If this Region is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getDistributors(Criteria criteria) throws TorqueException
    {
        if (collDistributors == null)
        {
            if (isNew())
            {
               collDistributors = new ArrayList();
            }
            else
            {
                   criteria.add(DistributorPeer.REGION_ID, getRegionId() );
                   collDistributors = DistributorPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(DistributorPeer.REGION_ID, getRegionId());
                   if (!lastDistributorsCriteria.equals(criteria))
                {
                    collDistributors = DistributorPeer.doSelect(criteria);
                }
            }
        }
        lastDistributorsCriteria = criteria;

        return collDistributors;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDistributors(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDistributors(Connection con) throws TorqueException
    {
        if (collDistributors == null)
        {
            collDistributors = getDistributors(new Criteria(10), con);
        }
        return collDistributors;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Region has previously
     * been saved, it will retrieve related Distributors from storage.
     * If this Region is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDistributors(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collDistributors == null)
        {
            if (isNew())
            {
               collDistributors = new ArrayList();
            }
            else
            {
                     criteria.add(DistributorPeer.REGION_ID, getRegionId());
                     collDistributors = DistributorPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(DistributorPeer.REGION_ID, getRegionId());
                     if (!lastDistributorsCriteria.equals(criteria))
                 {
                     collDistributors = DistributorPeer.doSelect(criteria, con);
                 }
             }
         }
         lastDistributorsCriteria = criteria;

         return collDistributors;
     }

      

     
      
      
          
                    
                
        
        
    
      
      
          
                    
                
        
        
    
      
         
          
                    
                
        
        
    
      
      
          
                    
                
        
        
      



             
      
    /**
     * Collection to store aggregation of collLocations
     */
    protected List collLocations;

    /**
     * Temporary storage of collLocations to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initLocations()
    {
        if (collLocations == null)
        {
            collLocations = new ArrayList();
        }
    }

    /**
     * Method called to associate a Location object to this object
     * through the Location foreign key attribute
     *
     * @param l Location
     * @throws TorqueException
     */
    public void addLocation(Location l) throws TorqueException
    {
        getLocations().add(l);
        l.setRegion((Region) this);
    }

    /**
     * The criteria used to select the current contents of collLocations
     */
    private Criteria lastLocationsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getLocations(new Criteria())
     *
     * @throws TorqueException
     */
    public List getLocations() throws TorqueException
    {
        if (collLocations == null)
        {
            collLocations = getLocations(new Criteria(10));
        }
        return collLocations;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Region has previously
     * been saved, it will retrieve related Locations from storage.
     * If this Region is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getLocations(Criteria criteria) throws TorqueException
    {
        if (collLocations == null)
        {
            if (isNew())
            {
               collLocations = new ArrayList();
            }
            else
            {
                   criteria.add(LocationPeer.REGION_ID, getRegionId() );
                   collLocations = LocationPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(LocationPeer.REGION_ID, getRegionId());
                   if (!lastLocationsCriteria.equals(criteria))
                {
                    collLocations = LocationPeer.doSelect(criteria);
                }
            }
        }
        lastLocationsCriteria = criteria;

        return collLocations;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getLocations(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getLocations(Connection con) throws TorqueException
    {
        if (collLocations == null)
        {
            collLocations = getLocations(new Criteria(10), con);
        }
        return collLocations;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Region has previously
     * been saved, it will retrieve related Locations from storage.
     * If this Region is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getLocations(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collLocations == null)
        {
            if (isNew())
            {
               collLocations = new ArrayList();
            }
            else
            {
                     criteria.add(LocationPeer.REGION_ID, getRegionId());
                     collLocations = LocationPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(LocationPeer.REGION_ID, getRegionId());
                     if (!lastLocationsCriteria.equals(criteria))
                 {
                     collLocations = LocationPeer.doSelect(criteria, con);
                 }
             }
         }
         lastLocationsCriteria = criteria;

         return collLocations;
     }

       

     
      
      
          
                    
                
        
        
    
      
      
          
                    
                
        
        
    
      
         
          
                    
                
        
        
    
      
      
          
                    
                
        
        
    
      
      
          
                    
                
        
        
      



     
    
     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(RegionPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                RegionPeer.doInsert((Region) this, con);
                setNew(false);
            }
            else
            {
                RegionPeer.doUpdate((Region) this, con);
            }
        }

                                    
                
          if (collDistributors != null)
          {
              for (int i = 0; i < collDistributors.size(); i++)
              {
                  ((Distributor) collDistributors.get(i)).save(con);
              }
          }
                                        
                
          if (collLocations != null)
          {
              for (int i = 0; i < collLocations.size(); i++)
              {
                  ((Location) collLocations.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  region_id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setRegionId(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setRegionId(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getRegionId());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Region copy() throws TorqueException
    {
        return copyInto(new Region());
    }

    protected Region copyInto(Region copyObj) throws TorqueException
    {
        copyObj.setRegionId(region_id);
        copyObj.setRegionName(region_name);

  copyObj.setNew(false);
                                    
                
        List v = getDistributors();
        for (int i = 0; i < v.size(); i++)
        {
            Distributor obj = (Distributor) v.get(i);
            copyObj.addDistributor(obj.copy());
            ((Persistent) v.get(i)).setNew(true);
        }
                                              
                
        v = getLocations();
        for (int i = 0; i < v.size(); i++)
        {
            Location obj = (Location) v.get(i);
            copyObj.addLocation(obj.copy());
            ((Persistent) v.get(i)).setNew(true);
        }
                copyObj.setNew(true);

                      copyObj.setRegionId(0);
                        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public RegionPeer getPeer()
    {
        return peer;
    }
}
