package org.campware.dream.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Jul 29 08:38:49 CEST 2004]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to Language
 */
public abstract class BaseLanguage extends BaseObject
{
    /** The Peer class */
    private static final LanguagePeer peer =
        new LanguagePeer();

                  
        /**
         * The value for the language_id field
         */
        private int language_id;
              
        /**
         * The value for the language_name field
         */
        private String language_name;
              
        /**
         * The value for the language_code field
         */
        private String language_code;
      
      
        /**
         * Get the LanguageId
         *
         * @return int
         */
        public int getLanguageId()
        {
            return language_id;
        }

                                                                              
        /**
         * Set the value of LanguageId
         *
         * @param v new value
         */
        public void setLanguageId(int v) throws TorqueException
        {
          


         if (this.language_id != v)
        {
             this.language_id = v;
            setModified(true);
        }

                  
                                                  
              // update associated Distributor
              if (collDistributors != null)
              {
                  for (int i = 0; i < collDistributors.size(); i++)
                  {
                      ((Distributor) collDistributors.get(i))
                          .setLanguageId(v);
                  }
              }
                                                              
              // update associated Dnewsletter
              if (collDnewslettersRelatedByDistLanguageId != null)
              {
                  for (int i = 0; i < collDnewslettersRelatedByDistLanguageId.size(); i++)
                  {
                      ((Dnewsletter) collDnewslettersRelatedByDistLanguageId.get(i))
                          .setDistLanguageId(v);
                  }
              }
                                                              
              // update associated Dnewsletter
              if (collDnewslettersRelatedByLanguageId != null)
              {
                  for (int i = 0; i < collDnewslettersRelatedByLanguageId.size(); i++)
                  {
                      ((Dnewsletter) collDnewslettersRelatedByLanguageId.get(i))
                          .setLanguageId(v);
                  }
              }
                                   }


        /**
         * Get the LanguageName
         *
         * @return String
         */
        public String getLanguageName()
        {
            return language_name;
        }

                                            
        /**
         * Set the value of LanguageName
         *
         * @param v new value
         */
        public void setLanguageName(String v) 
        {
          


         if (!ObjectUtils.equals(this.language_name, v))
        {
             this.language_name = v;
            setModified(true);
        }

                  
                       }


        /**
         * Get the LanguageCode
         *
         * @return String
         */
        public String getLanguageCode()
        {
            return language_code;
        }

                                            
        /**
         * Set the value of LanguageCode
         *
         * @param v new value
         */
        public void setLanguageCode(String v) 
        {
          


         if (!ObjectUtils.equals(this.language_code, v))
        {
             this.language_code = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collDistributors
     */
    protected List collDistributors;

    /**
     * Temporary storage of collDistributors to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initDistributors()
    {
        if (collDistributors == null)
        {
            collDistributors = new ArrayList();
        }
    }

    /**
     * Method called to associate a Distributor object to this object
     * through the Distributor foreign key attribute
     *
     * @param l Distributor
     * @throws TorqueException
     */
    public void addDistributor(Distributor l) throws TorqueException
    {
        getDistributors().add(l);
        l.setLanguage((Language) this);
    }

    /**
     * The criteria used to select the current contents of collDistributors
     */
    private Criteria lastDistributorsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDistributors(new Criteria())
     *
     * @throws TorqueException
     */
    public List getDistributors() throws TorqueException
    {
        if (collDistributors == null)
        {
            collDistributors = getDistributors(new Criteria(10));
        }
        return collDistributors;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Language has previously
     * been saved, it will retrieve related Distributors from storage.
     * If this Language is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getDistributors(Criteria criteria) throws TorqueException
    {
        if (collDistributors == null)
        {
            if (isNew())
            {
               collDistributors = new ArrayList();
            }
            else
            {
                   criteria.add(DistributorPeer.LANGUAGE_ID, getLanguageId() );
                   collDistributors = DistributorPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(DistributorPeer.LANGUAGE_ID, getLanguageId());
                   if (!lastDistributorsCriteria.equals(criteria))
                {
                    collDistributors = DistributorPeer.doSelect(criteria);
                }
            }
        }
        lastDistributorsCriteria = criteria;

        return collDistributors;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDistributors(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDistributors(Connection con) throws TorqueException
    {
        if (collDistributors == null)
        {
            collDistributors = getDistributors(new Criteria(10), con);
        }
        return collDistributors;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Language has previously
     * been saved, it will retrieve related Distributors from storage.
     * If this Language is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDistributors(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collDistributors == null)
        {
            if (isNew())
            {
               collDistributors = new ArrayList();
            }
            else
            {
                     criteria.add(DistributorPeer.LANGUAGE_ID, getLanguageId());
                     collDistributors = DistributorPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(DistributorPeer.LANGUAGE_ID, getLanguageId());
                     if (!lastDistributorsCriteria.equals(criteria))
                 {
                     collDistributors = DistributorPeer.doSelect(criteria, con);
                 }
             }
         }
         lastDistributorsCriteria = criteria;

         return collDistributors;
     }

      

     
      
      
          
                    
                
        
        
    
      
      
          
                    
                
        
        
    
      
      
          
                    
                
        
        
    
      
         
          
                    
                
        
        
      



                 
      
    /**
     * Collection to store aggregation of collDnewslettersRelatedByDistLanguageId
     */
    protected List collDnewslettersRelatedByDistLanguageId;

    /**
     * Temporary storage of collDnewslettersRelatedByDistLanguageId to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initDnewslettersRelatedByDistLanguageId()
    {
        if (collDnewslettersRelatedByDistLanguageId == null)
        {
            collDnewslettersRelatedByDistLanguageId = new ArrayList();
        }
    }

    /**
     * Method called to associate a Dnewsletter object to this object
     * through the Dnewsletter foreign key attribute
     *
     * @param l Dnewsletter
     * @throws TorqueException
     */
    public void addDnewsletterRelatedByDistLanguageId(Dnewsletter l) throws TorqueException
    {
        getDnewslettersRelatedByDistLanguageId().add(l);
        l.setLanguageRelatedByDistLanguageId((Language) this);
    }

    /**
     * The criteria used to select the current contents of collDnewslettersRelatedByDistLanguageId
     */
    private Criteria lastDnewslettersRelatedByDistLanguageIdCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDnewslettersRelatedByDistLanguageId(new Criteria())
     *
     * @throws TorqueException
     */
    public List getDnewslettersRelatedByDistLanguageId() throws TorqueException
    {
        if (collDnewslettersRelatedByDistLanguageId == null)
        {
            collDnewslettersRelatedByDistLanguageId = getDnewslettersRelatedByDistLanguageId(new Criteria(10));
        }
        return collDnewslettersRelatedByDistLanguageId;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Language has previously
     * been saved, it will retrieve related DnewslettersRelatedByDistLanguageId from storage.
     * If this Language is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getDnewslettersRelatedByDistLanguageId(Criteria criteria) throws TorqueException
    {
        if (collDnewslettersRelatedByDistLanguageId == null)
        {
            if (isNew())
            {
               collDnewslettersRelatedByDistLanguageId = new ArrayList();
            }
            else
            {
                   criteria.add(DnewsletterPeer.DIST_LANGUAGE_ID, getLanguageId() );
                   collDnewslettersRelatedByDistLanguageId = DnewsletterPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(DnewsletterPeer.DIST_LANGUAGE_ID, getLanguageId());
                   if (!lastDnewslettersRelatedByDistLanguageIdCriteria.equals(criteria))
                {
                    collDnewslettersRelatedByDistLanguageId = DnewsletterPeer.doSelect(criteria);
                }
            }
        }
        lastDnewslettersRelatedByDistLanguageIdCriteria = criteria;

        return collDnewslettersRelatedByDistLanguageId;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDnewslettersRelatedByDistLanguageId(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDnewslettersRelatedByDistLanguageId(Connection con) throws TorqueException
    {
        if (collDnewslettersRelatedByDistLanguageId == null)
        {
            collDnewslettersRelatedByDistLanguageId = getDnewslettersRelatedByDistLanguageId(new Criteria(10), con);
        }
        return collDnewslettersRelatedByDistLanguageId;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Language has previously
     * been saved, it will retrieve related DnewslettersRelatedByDistLanguageId from storage.
     * If this Language is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDnewslettersRelatedByDistLanguageId(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collDnewslettersRelatedByDistLanguageId == null)
        {
            if (isNew())
            {
               collDnewslettersRelatedByDistLanguageId = new ArrayList();
            }
            else
            {
                     criteria.add(DnewsletterPeer.DIST_LANGUAGE_ID, getLanguageId());
                     collDnewslettersRelatedByDistLanguageId = DnewsletterPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(DnewsletterPeer.DIST_LANGUAGE_ID, getLanguageId());
                     if (!lastDnewslettersRelatedByDistLanguageIdCriteria.equals(criteria))
                 {
                     collDnewslettersRelatedByDistLanguageId = DnewsletterPeer.doSelect(criteria, con);
                 }
             }
         }
         lastDnewslettersRelatedByDistLanguageIdCriteria = criteria;

         return collDnewslettersRelatedByDistLanguageId;
     }

        

     
      
      
          
                    
                
        
                
    
      
      
          
                    
                
        
                
    
      
      
          
                    
                
        
                
    
      
      
          
                    
                
        
                
    
      
         
              
                            
                
        
                        
    
      
         
              
                            
                
        
                
      



                 
      
    /**
     * Collection to store aggregation of collDnewslettersRelatedByLanguageId
     */
    protected List collDnewslettersRelatedByLanguageId;

    /**
     * Temporary storage of collDnewslettersRelatedByLanguageId to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initDnewslettersRelatedByLanguageId()
    {
        if (collDnewslettersRelatedByLanguageId == null)
        {
            collDnewslettersRelatedByLanguageId = new ArrayList();
        }
    }

    /**
     * Method called to associate a Dnewsletter object to this object
     * through the Dnewsletter foreign key attribute
     *
     * @param l Dnewsletter
     * @throws TorqueException
     */
    public void addDnewsletterRelatedByLanguageId(Dnewsletter l) throws TorqueException
    {
        getDnewslettersRelatedByLanguageId().add(l);
        l.setLanguageRelatedByLanguageId((Language) this);
    }

    /**
     * The criteria used to select the current contents of collDnewslettersRelatedByLanguageId
     */
    private Criteria lastDnewslettersRelatedByLanguageIdCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDnewslettersRelatedByLanguageId(new Criteria())
     *
     * @throws TorqueException
     */
    public List getDnewslettersRelatedByLanguageId() throws TorqueException
    {
        if (collDnewslettersRelatedByLanguageId == null)
        {
            collDnewslettersRelatedByLanguageId = getDnewslettersRelatedByLanguageId(new Criteria(10));
        }
        return collDnewslettersRelatedByLanguageId;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Language has previously
     * been saved, it will retrieve related DnewslettersRelatedByLanguageId from storage.
     * If this Language is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getDnewslettersRelatedByLanguageId(Criteria criteria) throws TorqueException
    {
        if (collDnewslettersRelatedByLanguageId == null)
        {
            if (isNew())
            {
               collDnewslettersRelatedByLanguageId = new ArrayList();
            }
            else
            {
                   criteria.add(DnewsletterPeer.LANGUAGE_ID, getLanguageId() );
                   collDnewslettersRelatedByLanguageId = DnewsletterPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(DnewsletterPeer.LANGUAGE_ID, getLanguageId());
                   if (!lastDnewslettersRelatedByLanguageIdCriteria.equals(criteria))
                {
                    collDnewslettersRelatedByLanguageId = DnewsletterPeer.doSelect(criteria);
                }
            }
        }
        lastDnewslettersRelatedByLanguageIdCriteria = criteria;

        return collDnewslettersRelatedByLanguageId;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getDnewslettersRelatedByLanguageId(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDnewslettersRelatedByLanguageId(Connection con) throws TorqueException
    {
        if (collDnewslettersRelatedByLanguageId == null)
        {
            collDnewslettersRelatedByLanguageId = getDnewslettersRelatedByLanguageId(new Criteria(10), con);
        }
        return collDnewslettersRelatedByLanguageId;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this Language has previously
     * been saved, it will retrieve related DnewslettersRelatedByLanguageId from storage.
     * If this Language is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getDnewslettersRelatedByLanguageId(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collDnewslettersRelatedByLanguageId == null)
        {
            if (isNew())
            {
               collDnewslettersRelatedByLanguageId = new ArrayList();
            }
            else
            {
                     criteria.add(DnewsletterPeer.LANGUAGE_ID, getLanguageId());
                     collDnewslettersRelatedByLanguageId = DnewsletterPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(DnewsletterPeer.LANGUAGE_ID, getLanguageId());
                     if (!lastDnewslettersRelatedByLanguageIdCriteria.equals(criteria))
                 {
                     collDnewslettersRelatedByLanguageId = DnewsletterPeer.doSelect(criteria, con);
                 }
             }
         }
         lastDnewslettersRelatedByLanguageIdCriteria = criteria;

         return collDnewslettersRelatedByLanguageId;
     }

        

     
      
      
          
                    
                
        
                
    
      
      
          
                    
                
        
                
    
      
      
          
                    
                
        
                
    
      
      
          
                    
                
        
                
    
      
         
              
                            
                
        
                
    
      
         
              
                            
                
        
                        
      



     
    
     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(LanguagePeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                LanguagePeer.doInsert((Language) this, con);
                setNew(false);
            }
            else
            {
                LanguagePeer.doUpdate((Language) this, con);
            }
        }

                                    
                
          if (collDistributors != null)
          {
              for (int i = 0; i < collDistributors.size(); i++)
              {
                  ((Distributor) collDistributors.get(i)).save(con);
              }
          }
                                                    
                
          if (collDnewslettersRelatedByDistLanguageId != null)
          {
              for (int i = 0; i < collDnewslettersRelatedByDistLanguageId.size(); i++)
              {
                  ((Dnewsletter) collDnewslettersRelatedByDistLanguageId.get(i)).save(con);
              }
          }
                                                    
                
          if (collDnewslettersRelatedByLanguageId != null)
          {
              for (int i = 0; i < collDnewslettersRelatedByLanguageId.size(); i++)
              {
                  ((Dnewsletter) collDnewslettersRelatedByLanguageId.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  language_id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setLanguageId(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setLanguageId(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getLanguageId());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public Language copy() throws TorqueException
    {
        return copyInto(new Language());
    }

    protected Language copyInto(Language copyObj) throws TorqueException
    {
        copyObj.setLanguageId(language_id);
        copyObj.setLanguageName(language_name);
        copyObj.setLanguageCode(language_code);

  copyObj.setNew(false);
                                    
                
        List v = getDistributors();
        for (int i = 0; i < v.size(); i++)
        {
            Distributor obj = (Distributor) v.get(i);
            copyObj.addDistributor(obj.copy());
            ((Persistent) v.get(i)).setNew(true);
        }
                                                          
                
        v = getDnewslettersRelatedByDistLanguageId();
        for (int i = 0; i < v.size(); i++)
        {
            Dnewsletter obj = (Dnewsletter) v.get(i);
            copyObj.addDnewsletterRelatedByDistLanguageId(obj.copy());
            ((Persistent) v.get(i)).setNew(true);
        }
                                                          
                
        v = getDnewslettersRelatedByLanguageId();
        for (int i = 0; i < v.size(); i++)
        {
            Dnewsletter obj = (Dnewsletter) v.get(i);
            copyObj.addDnewsletterRelatedByLanguageId(obj.copy());
            ((Persistent) v.get(i)).setNew(true);
        }
                copyObj.setNew(true);

                      copyObj.setLanguageId(0);
                            return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public LanguagePeer getPeer()
    {
        return peer;
    }
}
