package org.campware.dream.om;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;


/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Jul 29 08:38:49 CEST 2004]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to SalesArea
 */
public abstract class BaseSalesArea extends BaseObject
{
    /** The Peer class */
    private static final SalesAreaPeer peer =
        new SalesAreaPeer();

                  
        /**
         * The value for the sales_area_id field
         */
        private int sales_area_id;
              
        /**
         * The value for the sales_area_name field
         */
        private String sales_area_name;
      
      
        /**
         * Get the SalesAreaId
         *
         * @return int
         */
        public int getSalesAreaId()
        {
            return sales_area_id;
        }

                                                                              
        /**
         * Set the value of SalesAreaId
         *
         * @param v new value
         */
        public void setSalesAreaId(int v) throws TorqueException
        {
          


         if (this.sales_area_id != v)
        {
             this.sales_area_id = v;
            setModified(true);
        }

                  
                                                  
              // update associated SalesDistrict
              if (collSalesDistricts != null)
              {
                  for (int i = 0; i < collSalesDistricts.size(); i++)
                  {
                      ((SalesDistrict) collSalesDistricts.get(i))
                          .setSalesAreaId(v);
                  }
              }
                                   }


        /**
         * Get the SalesAreaName
         *
         * @return String
         */
        public String getSalesAreaName()
        {
            return sales_area_name;
        }

                                            
        /**
         * Set the value of SalesAreaName
         *
         * @param v new value
         */
        public void setSalesAreaName(String v) 
        {
          


         if (!ObjectUtils.equals(this.sales_area_name, v))
        {
             this.sales_area_name = v;
            setModified(true);
        }

                  
                       }


 
        
                
      
    /**
     * Collection to store aggregation of collSalesDistricts
     */
    protected List collSalesDistricts;

    /**
     * Temporary storage of collSalesDistricts to save a possible db hit in
     * the event objects are add to the collection, but the
     * complete collection is never requested.
     */
    protected void initSalesDistricts()
    {
        if (collSalesDistricts == null)
        {
            collSalesDistricts = new ArrayList();
        }
    }

    /**
     * Method called to associate a SalesDistrict object to this object
     * through the SalesDistrict foreign key attribute
     *
     * @param l SalesDistrict
     * @throws TorqueException
     */
    public void addSalesDistrict(SalesDistrict l) throws TorqueException
    {
        getSalesDistricts().add(l);
        l.setSalesArea((SalesArea) this);
    }

    /**
     * The criteria used to select the current contents of collSalesDistricts
     */
    private Criteria lastSalesDistrictsCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getSalesDistricts(new Criteria())
     *
     * @throws TorqueException
     */
    public List getSalesDistricts() throws TorqueException
    {
        if (collSalesDistricts == null)
        {
            collSalesDistricts = getSalesDistricts(new Criteria(10));
        }
        return collSalesDistricts;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this SalesArea has previously
     * been saved, it will retrieve related SalesDistricts from storage.
     * If this SalesArea is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException
     */
    public List getSalesDistricts(Criteria criteria) throws TorqueException
    {
        if (collSalesDistricts == null)
        {
            if (isNew())
            {
               collSalesDistricts = new ArrayList();
            }
            else
            {
                   criteria.add(SalesDistrictPeer.SALES_AREA_ID, getSalesAreaId() );
                   collSalesDistricts = SalesDistrictPeer.doSelect(criteria);
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                   criteria.add(SalesDistrictPeer.SALES_AREA_ID, getSalesAreaId());
                   if (!lastSalesDistrictsCriteria.equals(criteria))
                {
                    collSalesDistricts = SalesDistrictPeer.doSelect(criteria);
                }
            }
        }
        lastSalesDistrictsCriteria = criteria;

        return collSalesDistricts;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getSalesDistricts(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getSalesDistricts(Connection con) throws TorqueException
    {
        if (collSalesDistricts == null)
        {
            collSalesDistricts = getSalesDistricts(new Criteria(10), con);
        }
        return collSalesDistricts;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this SalesArea has previously
     * been saved, it will retrieve related SalesDistricts from storage.
     * If this SalesArea is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     */
    public List getSalesDistricts(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collSalesDistricts == null)
        {
            if (isNew())
            {
               collSalesDistricts = new ArrayList();
            }
            else
            {
                     criteria.add(SalesDistrictPeer.SALES_AREA_ID, getSalesAreaId());
                     collSalesDistricts = SalesDistrictPeer.doSelect(criteria, con);
             }
         }
         else
         {
             // criteria has no effect for a new object
             if (!isNew())
             {
                 // the following code is to determine if a new query is
                 // called for.  If the criteria is the same as the last
                 // one, just return the collection.
                     criteria.add(SalesDistrictPeer.SALES_AREA_ID, getSalesAreaId());
                     if (!lastSalesDistrictsCriteria.equals(criteria))
                 {
                     collSalesDistricts = SalesDistrictPeer.doSelect(criteria, con);
                 }
             }
         }
         lastSalesDistrictsCriteria = criteria;

         return collSalesDistricts;
     }

   

     
      
         
          
                    
                
        
        
      



     
    
     


    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
             save(SalesAreaPeer.getMapBuilder()
                .getDatabaseMap().getName());
     }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
     *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
         try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }

     }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
        if (!alreadyInSave)
      {
        alreadyInSave = true;



  
        // If this object has been modified, then save it to the database.
        if (isModified())
        {
            if (isNew())
            {
                SalesAreaPeer.doInsert((SalesArea) this, con);
                setNew(false);
            }
            else
            {
                SalesAreaPeer.doUpdate((SalesArea) this, con);
            }
        }

                                    
                
          if (collSalesDistricts != null)
          {
              for (int i = 0; i < collSalesDistricts.size(); i++)
              {
                  ((SalesDistrict) collSalesDistricts.get(i)).save(con);
              }
          }
                  alreadyInSave = false;
      }
      }


                        
    
    

        /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  sales_area_id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        throws TorqueException
    {
                    setSalesAreaId(((NumberKey) key).intValue());
            }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) throws TorqueException
    {
                    setSalesAreaId(Integer.parseInt(key));
            }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
        return SimpleKey.keyFor(getSalesAreaId());
    }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     */
    public SalesArea copy() throws TorqueException
    {
        return copyInto(new SalesArea());
    }

    protected SalesArea copyInto(SalesArea copyObj) throws TorqueException
    {
        copyObj.setSalesAreaId(sales_area_id);
        copyObj.setSalesAreaName(sales_area_name);

  copyObj.setNew(false);
                                    
                
        List v = getSalesDistricts();
        for (int i = 0; i < v.size(); i++)
        {
            SalesDistrict obj = (SalesDistrict) v.get(i);
            copyObj.addSalesDistrict(obj.copy());
            ((Persistent) v.get(i)).setNew(true);
        }
                copyObj.setNew(true);

                      copyObj.setSalesAreaId(0);
                        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public SalesAreaPeer getPeer()
    {
        return peer;
    }
}
