package org.campware.dream.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Jul 29 08:38:49 CEST 2004]
  *
  */
public class DcontractItemMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.campware.dream.om.map.DcontractItemMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        if (dbMap != null)
        {
            return true;
        }
        return false;
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("dream");

        dbMap.addTable("DCONTRACT_ITEM");
        TableMap tMap = dbMap.getTable("DCONTRACT_ITEM");

                tMap.setPrimaryKeyMethod(TableMap.NATIVE);
        
                tMap.setPrimaryKeyMethodInfo("DCONTRACT_ITEM_SEQ");
        
                                      tMap.addPrimaryKey("DCONTRACT_ITEM.DCONTRACT_ITEM_ID", new Integer(0));
                                                        tMap.addForeignKey(
                "DCONTRACT_ITEM.DCONTRACT_ID", new Integer(0) , "DCONTRACT" ,
                    "DCONTRACT_ID");
                                                        tMap.addForeignKey(
                "DCONTRACT_ITEM.COST_TYPE_ID", new Integer(0) , "COST_TYPE" ,
                    "COST_TYPE_ID");
                                                        tMap.addColumn("DCONTRACT_ITEM.COST_FUNCTION", new Integer(0));
                                                        tMap.addColumn("DCONTRACT_ITEM.COST_AMOUNT", new BigDecimal(0));
                              }
}
