package org.campware.dream.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Jul 29 08:38:49 CEST 2004]
  *
  */
public class DcontractMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.campware.dream.om.map.DcontractMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        if (dbMap != null)
        {
            return true;
        }
        return false;
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("dream");

        dbMap.addTable("DCONTRACT");
        TableMap tMap = dbMap.getTable("DCONTRACT");

                tMap.setPrimaryKeyMethod(TableMap.NATIVE);
        
                tMap.setPrimaryKeyMethodInfo("DCONTRACT_SEQ");
        
                                      tMap.addPrimaryKey("DCONTRACT.DCONTRACT_ID", new Integer(0));
                                                        tMap.addColumn("DCONTRACT.DCONTRACT_CODE", new String());
                                                        tMap.addColumn("DCONTRACT.STATUS", new Integer(0));
                                                        tMap.addColumn("DCONTRACT.ISSUED_DATE", new Date());
                                                        tMap.addColumn("DCONTRACT.CLOSED_DATE", new Date());
                                                        tMap.addForeignKey(
                "DCONTRACT.DISTRIBUTOR_ID", new Integer(0) , "DISTRIBUTOR" ,
                    "DISTRIBUTOR_ID");
                                                        tMap.addForeignKey(
                "DCONTRACT.PROJECT_ID", new Integer(0) , "PROJECT" ,
                    "PROJECT_ID");
                                                        tMap.addColumn("DCONTRACT.START_DATE", new Date());
                                                        tMap.addColumn("DCONTRACT.END_DATE", new Date());
                                                        tMap.addColumn("DCONTRACT.NOTES", new String());
                                                        tMap.addColumn("DCONTRACT.CREATED", new Date());
                                                        tMap.addColumn("DCONTRACT.MODIFIED", new Date());
                                                        tMap.addColumn("DCONTRACT.CREATED_BY", new String());
                                                        tMap.addColumn("DCONTRACT.MODIFIED_BY", new String());
                              }
}
