package org.campware.dream.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Jul 29 08:38:49 CEST 2004]
  *
  */
public class DistributorMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.campware.dream.om.map.DistributorMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        if (dbMap != null)
        {
            return true;
        }
        return false;
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("dream");

        dbMap.addTable("DISTRIBUTOR");
        TableMap tMap = dbMap.getTable("DISTRIBUTOR");

                tMap.setPrimaryKeyMethod(TableMap.NATIVE);
        
                tMap.setPrimaryKeyMethodInfo("DISTRIBUTOR_SEQ");
        
                                      tMap.addPrimaryKey("DISTRIBUTOR.DISTRIBUTOR_ID", new Integer(0));
                                                        tMap.addColumn("DISTRIBUTOR.DISTRIBUTOR_CODE", new String());
                                                        tMap.addColumn("DISTRIBUTOR.STATUS", new Integer(0));
                                                        tMap.addColumn("DISTRIBUTOR.DISTRIBUTOR_NAME_1", new String());
                                                        tMap.addColumn("DISTRIBUTOR.DISTRIBUTOR_NAME_2", new String());
                                                        tMap.addColumn("DISTRIBUTOR.DISTRIBUTOR_DISPLAY", new String());
                                                        tMap.addColumn("DISTRIBUTOR.DEAR", new String());
                                                        tMap.addColumn("DISTRIBUTOR.DISTRIBUTOR_TYPE", new Integer(0));
                                                        tMap.addColumn("DISTRIBUTOR.GENDER", new Integer(0));
                                                        tMap.addForeignKey(
                "DISTRIBUTOR.DISTRIBUTOR_CAT_ID", new Integer(0) , "DISTRIBUTOR_CATEGORY" ,
                    "DISTRIBUTOR_CAT_ID");
                                                        tMap.addForeignKey(
                "DISTRIBUTOR.LANGUAGE_ID", new Integer(0) , "LANGUAGE" ,
                    "LANGUAGE_ID");
                                                        tMap.addColumn("DISTRIBUTOR.ADDRESS_1", new String());
                                                        tMap.addColumn("DISTRIBUTOR.ADDRESS_2", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CITY", new String());
                                                        tMap.addColumn("DISTRIBUTOR.ZIP", new String());
                                                        tMap.addColumn("DISTRIBUTOR.STATE", new String());
                                                        tMap.addForeignKey(
                "DISTRIBUTOR.COUNTRY_ID", new Integer(0) , "COUNTRY" ,
                    "COUNTRY_ID");
                                                        tMap.addForeignKey(
                "DISTRIBUTOR.REGION_ID", new Integer(0) , "REGION" ,
                    "REGION_ID");
                                                        tMap.addColumn("DISTRIBUTOR.PHONE_1", new String());
                                                        tMap.addColumn("DISTRIBUTOR.PHONE_2", new String());
                                                        tMap.addColumn("DISTRIBUTOR.FAX", new String());
                                                        tMap.addColumn("DISTRIBUTOR.EMAIL", new String());
                                                        tMap.addColumn("DISTRIBUTOR.EMAIL_FORMAT", new Integer(0));
                                                        tMap.addColumn("DISTRIBUTOR.SEND_NEWS", new Integer(0));
                                                        tMap.addColumn("DISTRIBUTOR.WEB_URL", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CUSTOM_1", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CUSTOM_2", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CUSTOM_3", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CUSTOM_4", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CUSTOM_5", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CUSTOM_6", new String());
                                                        tMap.addColumn("DISTRIBUTOR.NOTES", new String());
                                                        tMap.addColumn("DISTRIBUTOR.CREATED", new Date());
                                                        tMap.addColumn("DISTRIBUTOR.MODIFIED", new Date());
                                                        tMap.addColumn("DISTRIBUTOR.CREATED_BY", new String());
                                                        tMap.addColumn("DISTRIBUTOR.MODIFIED_BY", new String());
                              }
}
