package org.campware.dream.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Thu Jul 29 08:38:49 CEST 2004]
  *
  */
public class DoutboxEventMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.campware.dream.om.map.DoutboxEventMapBuilder";


    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        if (dbMap != null)
        {
            return true;
        }
        return false;
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("dream");

        dbMap.addTable("DOUTBOX_EVENT");
        TableMap tMap = dbMap.getTable("DOUTBOX_EVENT");

                tMap.setPrimaryKeyMethod(TableMap.NATIVE);
        
                tMap.setPrimaryKeyMethodInfo("DOUTBOX_EVENT_SEQ");
        
                                      tMap.addPrimaryKey("DOUTBOX_EVENT.DOUTBOX_EVENT_ID", new Integer(0));
                                                        tMap.addColumn("DOUTBOX_EVENT.DOUTBOX_EVENT_CODE", new String());
                                                        tMap.addColumn("DOUTBOX_EVENT.STATUS", new Integer(0));
                                                        tMap.addColumn("DOUTBOX_EVENT.PRIORITY", new Integer(0));
                                                        tMap.addColumn("DOUTBOX_EVENT.ISSUED_DATE", new Date());
                                                        tMap.addColumn("DOUTBOX_EVENT.CLOSED_DATE", new Date());
                                                        tMap.addColumn("DOUTBOX_EVENT.SENT_TIME", new Date());
                                                        tMap.addColumn("DOUTBOX_EVENT.EVENT_CHANNEL", new Integer(0));
                                                        tMap.addColumn("DOUTBOX_EVENT.EVENT_TYPE", new Integer(0));
                                                        tMap.addColumn("DOUTBOX_EVENT.EMAIL_FORMAT", new Integer(0));
                                                        tMap.addForeignKey(
                "DOUTBOX_EVENT.DISTRIBUTOR_ID", new Integer(0) , "DISTRIBUTOR" ,
                    "DISTRIBUTOR_ID");
                                                        tMap.addForeignKey(
                "DOUTBOX_EVENT.PROJECT_ID", new Integer(0) , "PROJECT" ,
                    "PROJECT_ID");
                                                        tMap.addForeignKey(
                "DOUTBOX_EVENT.PRODUCT_ID", new Integer(0) , "PRODUCT" ,
                    "PRODUCT_ID");
                                                        tMap.addColumn("DOUTBOX_EVENT.RECEIVER", new String());
                                                        tMap.addColumn("DOUTBOX_EVENT.SUBJECT", new String());
                                                        tMap.addColumn("DOUTBOX_EVENT.BODY", new String());
                                                        tMap.addColumn("DOUTBOX_EVENT.NOTES", new String());
                                                        tMap.addColumn("DOUTBOX_EVENT.CREATED", new Date());
                                                        tMap.addColumn("DOUTBOX_EVENT.MODIFIED", new Date());
                                                        tMap.addColumn("DOUTBOX_EVENT.CREATED_BY", new String());
                                                        tMap.addColumn("DOUTBOX_EVENT.MODIFIED_BY", new String());
                              }
}
